Repository futo-org/grayjay-android, pull requests merged in 2025-05, with the labels that each got.

#2136 Fix "previous song" button playing always from unshuffled queue, even when shuffle is used
  app/src/main/java/com/futo/platformplayer/states/StatePlayer.kt
Labels: Enhancement, CLA-signed

#1724 feat(player): Add a setting to adjust player seek duration
  app/src/main/java/com/futo/platformplayer/Settings.kt
  app/src/main/java/com/futo/platformplayer/views/behavior/GestureControlView.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: Enhancement, UI/UX, Core, CLA-signed, Android

#1803 fix link typo for Script Signing
  plugin-development.md
Labels: Documentation, CLA-not-signed

#2288 Fixed typo
  app/src/main/java/com/futo/platformplayer/states/StateDownloads.kt
Labels: CLA-signed
